name: Environment Echo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to echo message (dev or test)'
        required: true
        default: 'dev'
        options:
          - dev
          - test

jobs:
  dev-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo in Dev Environment
        run: echo "Hello from the Dev environment!"
        if: ${{ github.event.inputs.environment == 'dev' }}

  test-echo:
    runs-on: ubuntu-latest
    needs: dev-echo

    steps:
      - name: Echo in Test Environment
        run: echo "Hello from the Test environment!"
        if: ${{ github.event.inputs.environment == 'test' }}
